resolver: lts-19.32
packages:
- foo-bar-api
- foo-bar-api-gen
- foo-bar-api-server
- foo-bar-api-server-gen
- foo-bar-cli
- foo-bar-client

extra-deps:
- autodocodec-yaml-0.2.0.2@sha256:8f9981085572af2aa827e9fa92881d8cabd2a72e407dbd2e8efb06ea96cc34fa,1211
- safe-coloured-text-0.2.0.1@sha256:cb01d89f7c1ec009f8341c5b83c880a3798928beca3254a47d161d6ef0fb0165,1104


system-ghc: true
nix:
  enable: false
with-hpack: hpack
