name:                template-client
version:             0.0.0.0
github:              "NorfairKing/template-api-cli-login"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - servant
    - servant-client-core
    - servant-client
    - servant-auth
    - text
    - validity
    - validity-text
    - template-api

tests:
  template-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - template-api
