name:                template-api-server
version:             0.0.0.0
github:              "NorfairKing/template-api-cli-login"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - mtl
    - persistent
    - persistent-sqlite
    - servant-server
    - template-api
    - text
    - wai
    - warp

tests:
  template-api-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-hspec
    - hspec
    - http-client
    - monad-logger
    - persistent
    - persistent-sqlite
    - servant-client
    - template-api
    - template-api-gen
    - template-api-server
    - template-client
    - warp
